# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffb4a0e86b307b84f159f5ae8eb7062272e72efbf93dc44be8a5b69b6ec16506fb7edb24832870ed3bbc54dcfc47fb6f9b0776e5e7c21dfdfd182374ce9c7f4c

test:
  secret_key_base: 42aa924044fba9f1cb83094405f327254c87087d770eab179174cb7644b5d48633b48bc1ce7c34a8c291731dcbbb90755f1bd98af105457fc0e90f9f94093e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
